name: Build Mimage Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Debian Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper dpkg-dev lintian fakeroot rsync

      - name: Extract Versioning Info
        id: pkg_info
        run: |
          DEB_VERSION=$(grep -i '^Version:' debian/changelog | head -n 1 | sed -e 's/.*(\(.*\)).*/\1/')
          UPSTREAM_VERSION=$(echo $DEB_VERSION | cut -d'-' -f1)

          echo "DEB_VERSION=$DEB_VERSION" >> $GITHUB_ENV
          echo "UPSTREAM_VERSION=$UPSTREAM_VERSION" >> $GITHUB_ENV

      - name: Prepare Strict Debian Build Environment
        run: |
          mkdir -p build_env/mimage-${UPSTREAM_VERSION}

          # copies everythng (except .git folder obviously)
          rsync -a --exclude='.git' --exclude='build_env' ./ build_env/mimage-${UPSTREAM_VERSION}/

          cd build_env
          # original tar
          tar -cJvf mimage_${UPSTREAM_VERSION}.orig.tar.xz --exclude='debian' mimage-${UPSTREAM_VERSION}/

      - name: Build Debian Package (debuild)
        run: |
          cd build_env/mimage-${UPSTREAM_VERSION}
          debuild -us -uc

      - name: Quality Assurance (Lintian)
        run: |
          cd build_env
          #  lintian on generated .changes
          lintian -EviIL +pedantic mimage_${DEB_VERSION}_amd64.changes || true

      - name: Create Source Code Archives
        run: |
          # git archive for creating clean zip 'n tar.gz
          git archive --format=zip --output=mimage_${UPSTREAM_VERSION}_source.zip HEAD
          git archive --format=tar.gz --output=mimage_${UPSTREAM_VERSION}_source.tar.gz HEAD

      - name: Upload Debian Packages (.deb, .changes, .buildinfo)
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: |
            build_env/*.deb
            build_env/*.changes
            build_env/*.buildinfo

      - name: Upload Source Archives
        uses: actions/upload-artifact@v4
        with:
          name: source-archives
          path: |
            mimage_*_source.zip
            mimage_*_source.tar.gz
